### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by zytek** [zendesk/goship#3]
```
➜  ~ goship ssh --uncache .
Cache refresh total time: 2.434µs

Could not find any matches for identifier 

➜  ~ goship ssh .
Cache refresh total time: 2.735µs

Could not find any matches for identifier

➜  ~ ls -l /Users/zytek/tmp/
➜  ~
```

1. cache file is not created
2. no error reported
3. aws credentials DO have default profile and region set

```
➜  ~ cat ~/.goship.yaml
username: ec2-user
use_private_network: true
use_dns: true
cache_directory: /Users/zytek/tmp/
cache_file_prefix: /usr/bin/scp
cache_validity: 300
verbose: false
ssh_binary: /usr/bin/ssh
ssh_extra_params: []
scp_binary: /usr/bin/scp
scp_extra_params: []
```

aws config:

```
➜  ~ grep -A3 default ~/.aws/c*
/Users/zytek/.aws/config:[default]
/Users/zytek/.aws/config-region=eu-west-1
--
/Users/zytek/.aws/credentials:[default]
/Users/zytek/.aws/credentials-aws_access_key_id = x
/Users/zytek/.aws/credentials-aws_secret_access_key = x
/Users/zytek/.aws/credentials-region = eu-west-1
```

**Comment by emate** [comment]
@zytek do you have any cloud provider configured in `goship.yaml` config file? Check out the `config.yaml.example` file and look at the `providers` section.

**Comment by docent-net** [comment]
Same here. I'd expect a warning message related to the unconfigured provider.

Also, it'd be great to have default AWS provider since its the only one :)

**Comment by zytek** [comment]
```
providers:
    aws.ec2:
      - profile: default
        regions: us-east-1
```

```
➜  ~ goship find .
panic: interface conversion: interface {} is string, not []interface {}

goroutine 1 [running]:
github.com/zendesk/goship/providers.InitAwsEc2ProvidersFromCfg(0xc000190e40, 0xc0001910e0, 0xc0001439a8, 0x302030303020303, 0x0, 0x0)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/providers/aws_ec2.go:26 +0x3b9
github.com/zendesk/goship/providers.InitProvidersFromConfig(0xc000191170, 0xc000143ad8, 0x10ddaf9, 0xc000143b30, 0x100d2bf, 0xc0000ccaa0)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/providers/provider.go:24 +0x1c8
github.com/zendesk/goship/cmd.initCaches(0x0, 0x0, 0x5010100)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/cmd/util.go:54 +0x42
github.com/zendesk/goship/cmd.getCacheList(0xc000143cd0, 0x100e71d, 0x17d8dc0)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/cmd/util.go:72 +0x34
github.com/zendesk/goship/cmd.findCmdFunc(0x1eb6420, 0xc0001a44b0, 0x1, 0x1)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/cmd/find.go:24 +0x26
github.com/zendesk/goship/vendor/github.com/spf13/cobra.(*Command).execute(0x1eb6420, 0xc0001a4470, 0x1, 0x1, 0x1eb6420, 0xc0001a4470)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/zendesk/goship/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1eb5fe0, 0x0, 0x1eb6ca0, 0xc000143f58)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/zendesk/goship/vendor/github.com/spf13/cobra.(*Command).Execute(0x1eb5fe0, 0x1007220, 0xc000092058)
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/zendesk/goship/cmd.Execute()
	/Users/mmatlaszek/GO/src/github.com/zendesk/goship/cmd/cli.go:42 +0x2d
main.main()
	/Users/mmatlaszek/GIT/zendesk/goship/main.go:10 +0x25
```
